In [1]:
import pandas as pd

In [5]:
pf=pd.read_csv("laptops3.csv", sep=";")

# Задание1

Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU

In [10]:
pf['Cpu'].value_counts()
# cpu=pf[pf['Cpu']==]
# pf['Cpu_Company']=

Intel Core i5 7200U 2.5GHz       190
Intel Core i7 7700HQ 2.8GHz      146
Intel Core i7 7500U 2.7GHz       134
Intel Core i7 8550U 1.8GHz        73
Intel Core i5 8250U 1.6GHz        72
                                ...
Intel Core M M3-6Y30 0.9GHz        1
AMD A9-Series 9420 2.9GHz          1
Intel Core i3 6006U 2.2GHz         1
AMD A6-Series 7310 2GHz            1
Intel Xeon E3-1535M v6 3.1GHz      1
Name: Cpu, Length: 118, dtype: int64

In [17]:
Cpu_Company = []
for i,row in pf.iterrows():
    Cpu_Company.append(row['Cpu'].split(' ')[0])
    
pf['Cpu_Company'] = Cpu_Company
pf.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

In [26]:
pf['Cpu_Company']=pf['Cpu'].apply(lambda x:x.split(' ')[0])

In [27]:
pf.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128GB,"[128GB, SSD]"
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128GB,"[128GB, Flash, Storage]"
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256GB,"[256GB, SSD]"
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512GB,"[512GB, SSD]"
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256GB,"[256GB, SSD]"

# Задание2

Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя

In [45]:
Memory_Amount = []
for i,row in pf.iterrows():
    if 'GB' in row['Memory'].split(' ')[0]:
        Memory_Amount.append(int(row['Memory'].split(' ')[0].replace('GB', '')))
    elif 'TB' in row['Memory'].split(' ')[0]:
         Memory_Amount.append(int(float(row['Memory'].split(' ')[0].replace('TB', ''))*1024))
                                                    
pf['Memory_Amount'] = Memory_Amount
pf['Memory_Amount'].value_counts()
# pf['Memory_Amount'].dtype

256     508
1024    250
128     177
512     140
500     132
32       45
64       17
2048     16
16       10
180       5
240       1
8         1
508       1
Name: Memory_Amount, dtype: int64

In [49]:
def mem(x):
    a=x.split(' ')[0]
    if a.endswith('GB'):
        res=a.replace('GB', '')
    elif a.endswith('TB'):    
        res=float(a.replace('TB', ''))*1024
    return int(res)    

pf['Memory_Amount2']=pf['Memory'].apply(mem)
# pf

# Задание3

1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.)

In [62]:
pf['Memory_Type']=pf['Memory'].apply(lambda x:' '.join(x.split(' ')[1:]))
pf['Memory_Type'].value_counts()

SSD                         637
HDD                         374
SSD +  1TB HDD              183
Flash Storage                74
SSD +  2TB HDD               15
Hybrid                       10
SSD +  256GB SSD              3
SSD +  500GB HDD              2
SSD +  1.0TB Hybrid           2
SSD +  512GB SSD              1
Flash Storage +  1TB HDD      1
HDD +  1TB HDD                1
Name: Memory_Type, dtype: int64

In [64]:
def mem1(x):
    listX=['SSD', 'HDD', 'Flash Storage','Hybrid']
    res=''
    for i in listX:
        if i in x:
            res+=' '+i
    return res
    

pf['Memory_Amount2']=pf['Memory'].apply(mem1)
pf['Memory_Amount2'].value_counts()

 SSD                  641
 HDD                  375
 SSD HDD              200
 Flash Storage         74
 Hybrid                10
 SSD Hybrid             2
 HDD Flash Storage      1
Name: Memory_Amount2, dtype: int64

In [58]:
pf['Memory'].value_counts()

256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: Memory, dtype: int64

# Задание4
1.4 Удалите признаки Memory и ScreenResolution

In [67]:
pf.drop(columns=['Memory', 'ScreenResolution'], inplace=True)
# pf.drop(columns='ScreenResolution')
pf.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,Memory_Amount2
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,SSD
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,Flash Storage
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,SSD
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,SSD

## Задание 2.
#### 2.1 Создайте признак SSD, который изначально равен 0

In [68]:
pf['SSD']=0
pf.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,Memory_Amount2,SSD
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,SSD,0
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,Flash Storage,0
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,SSD,0
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,SSD,0
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,SSD,0

#### 2.2 Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD

In [70]:
pf.loc[pf['Memory_Type'] == 'SSD', 'SSD'] = 1
pf.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,Memory_Amount2,SSD
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,SSD,1
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,Flash Storage,0
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,SSD,1
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,SSD,1
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,SSD,1

#### 2.3 Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [83]:
# pf['Weight'].dtype
#pf['Weight'] = pf['Weight'].str.replace('kg', '').astype('float')
pf

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,Memory_Amount2,SSD
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,SSD,1
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,Flash Storage,Flash Storage,0
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD,SSD,1
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD,SSD,1
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD,SSD,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Intel Core i7 6500U 2.5GHz,4GB,Intel HD Graphics 520,Windows 10,1.80,638.00,Intel,128,SSD,SSD,1
1299,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.30,1499.00,Intel,512,SSD,SSD,1
1300,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Intel Celeron Dual Core N3050 1.6GHz,2GB,Intel HD Graphics,Windows 10,1.50,229.00,Intel,64,Flash Storage,Flash Storage,0
1301,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Intel Core i7 6500U 2.5GHz,6GB,AMD Radeon R5 M330,Windows 10,2.19,764.00,Intel,1024,HDD,HDD,0
1302,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,Intel Celeron Dual Core N3050 1.6GHz,4GB,Intel HD Graphics,Windows 10,2.20,369.00,Intel,500,HDD,HDD,0

# Задание 3.

Создайте датафрейм с клиентами:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
})

In [84]:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
})

In [86]:
clients

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

#### 3.1 Присоедините к таблице clients данные по ноутбукам через метод join

In [87]:
clients_lap_id = clients.set_index('laptop_id')
clients_lap_id

           client_id
laptop_id
506               45
398               32
710               67
120               33
1999              43

In [88]:
joined = clients_lap_id.join(pf)
joined

,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,Memory_Amount2,SSD
laptop_id,,,,,,,,,,,,,,,,
506,45,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256.0,SSD + 1TB HDD,SSD HDD,0.0
398,32,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256.0,SSD,SSD,1.0
710,67,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128.0,SSD + 1TB HDD,SSD HDD,0.0
120,33,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024.0,HDD,HDD,0.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 3.2 Присоедините к таблице clients данные по ноутбукам через метод merge

In [89]:
pf['laptop_id']=pf.index

In [93]:
merged = clients_lap_id.merge(pf, on='laptop_id')
# merged_left = bank.merge(users, on='CustomerId', how='left')
merged

,laptop_id,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,Memory_Amount2,SSD
0,506,45,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256,SSD + 1TB HDD,SSD HDD,0
1,398,32,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256,SSD,SSD,1
2,710,67,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128,SSD + 1TB HDD,SSD HDD,0
3,120,33,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024,HDD,HDD,0

# Задание 4.

#### Найдите среднюю стоимость ноутбуков в зависимости от компании производителя
Отсортируйте от меньшей стоимости к большей

In [94]:
grouped = pf.groupby('Company')
grouped

In [95]:
grouped.groups

{'Acer': [5, 9, 36, 43, 51, 54, 74, 78, 84, 91, 95, 120, 124, 132, 133, 140, 149, 161, 164, 166, 168, 176, 188, 202, 210, 225, 234, 236, 239, 254, 277, 284, 285, 290, 296, 313, 319, 324, 326, 371, 379, 392, 403, 413, 446, 460, 461, 466, 493, 507, 511, 543, 560, 602, 609, 619, 644, 646, 651, 669, 679, 690, 695, 706, 730, 733, 739, 745, 759, 765, 769, 777, 788, 828, 829, 868, 888, 907, 914, 942, 949, 959, 962, 997, 1000, 1031, 1057, 1089, 1095, 1102, 1134, 1183, 1187, 1189, 1198, 1208, 1215, 1216, 1219, 1242, ...], 'Apple': [0, 1, 3, 4, 6, 7, 12, 14, 15, 17, 26, 34, 45, 81, 249, 270, 794, 1069, 1193, 1210, 1234], 'Asus': [8, 20, 31, 40, 42, 47, 49, 57, 59, 63, 65, 69, 75, 88, 90, 94, 98, 107, 110, 118, 119, 127, 137, 145, 147, 157, 160, 211, 227, 228, 230, 237, 238, 241, 242, 247, 251, 252, 266, 271, 287, 291, 299, 300, 301, 304, 314, 322, 327, 332, 334, 338, 348, 361, 370, 372, 378, 382, 384, 390, 391, 401, 405, 414, 423, 435, 439, 462, 465, 474, 489, 492, 494, 500, 506, 515, 517, 519, 532, 534, 544, 555, 564, 589, 590, 615, 628, 630, 634, 635, 643, 650, 676, 681, 697, 713, 752, 754, 763, 766, ...], 'Chuwi': [30, 421, 483], 'Dell': [13, 16, 19, 23, 25, 27, 28, 33, 37, 41, 44, 48, 55, 60, 61, 71, 72, 77, 80, 85, 89, 93, 96, 97, 102, 111, 114, 117, 128, 130, 131, 150, 151, 158, 162, 167, 175, 180, 181, 185, 186, 189, 194, 200, 204, 206, 207, 208, 215, 218, 219, 220, 224, 226, 233, 235, 243, 245, 250, 255, 260, 263, 264, 265, 272, 275, 276, 281, 293, 297, 311, 315, 329, 336, 339, 340, 344, 347, 349, 350, 355, 357, 358, 359, 366, 368, 374, 377, 387, 388, 394, 398, 407, 415, 416, 418, 424, 425, 426, 427, ...], 'Fujitsu': [567, 623, 983], 'Google': [437, 472, 762], 'HP': [2, 10, 11, 22, 24, 29, 32, 38, 39, 52, 53, 56, 64, 66, 67, 79, 82, 86, 87, 92, 99, 100, 101, 103, 105, 113, 115, 116, 123, 125, 126, 129, 134, 135, 139, 144, 146, 154, 155, 169, 171, 174, 179, 195, 197, 198, 199, 212, 217, 223, 229, 231, 246, 248, 256, 257, 262, 268, 292, 306, 309, 316, 318, 320, 323, 328, 335, 337, 342, 346, 351, 353, 360, 363, 365, 369, 375, 380, 395, 412, 417, 422, 428, 436, 444, 450, 452, 459, 468, 470, 471, 482, 497, 501, 508, 516, 518, 521, 523, 537, ...], 'Huawei': [170, 214], 'LG': [678, 905, 909], 'Lenovo': [18, 21, 35, 46, 50, 62, 68, 76, 83, 106, 109, 112, 122, 136, 138, 141, 142, 152, 156, 163, 172, 178, 182, 187, 190, 193, 201, 203, 205, 209, 213, 216, 221, 232, 240, 244, 253, 259, 261, 267, 269, 273, 278, 279, 280, 282, 283, 286, 288, 289, 294, 295, 298, 302, 303, 305, 308, 310, 317, 321, 325, 333, 341, 343, 345, 356, 362, 364, 367, 373, 376, 381, 383, 385, 386, 389, 396, 397, 399, 400, 402, 408, 409, 410, 411, 419, 420, 431, 432, 433, 434, 438, 440, 442, 443, 453, 463, 464, 469, 477, ...], 'MSI': [58, 73, 108, 121, 148, 153, 165, 177, 258, 312, 330, 352, 393, 404, 448, 578, 585, 603, 605, 618, 653, 664, 675, 680, 724, 738, 785, 786, 811, 823, 894, 917, 919, 937, 1032, 1047, 1059, 1064, 1077, 1097, 1106, 1138, 1141, 1156, 1161, 1169, 1178, 1199, 1212, 1221, 1229, 1233, 1238, 1259], 'Mediacom': [429, 533, 556, 575, 580, 626, 718], 'Microsoft': [70, 104, 449, 457, 458, 670], 'Razer': [196, 647, 778, 816, 830, 1117, 1231], 'Samsung': [430, 593, 746, 768, 771, 812, 874, 892, 1191], 'Toshiba': [143, 159, 173, 183, 222, 274, 307, 331, 354, 406, 479, 491, 531, 576, 606, 648, 655, 665, 668, 694, 698, 742, 772, 782, 806, 821, 825, 837, 862, 866, 872, 895, 923, 934, 943, 952, 960, 963, 973, 981, 984, 1004, 1015, 1018, 1021, 1037, 1042, 1118], 'Vero': [191, 791, 1041, 1120], 'Xiaomi': [184, 192, 514, 877]}

In [129]:
# pf.groupby('Company').agg({'Price_euros': 'mean'}).sort_values('Price_euros')
aa=pf.groupby('Company').agg({'Price_euros': 'mean'})
aa.sort_values(by='Price_euros')
# aa

# aa=grouped.agg({'Price_euros': 'mean'})
# aa.sort_values(by='Price_euros')


# grouped.agg({'Price_euros': ['sum', 'min', 'max']})
# users.groupby('Geography').agg({'Age': ['mean'], 'EstimatedSalary': ['min']})
#aa = grouped.agg({'Price_euros': ['mean']}).sort('Price_euros')
# aa.columns
# aa.sort_values(by='Price_euros')
# pf['Memory_Amount'].dtype
# aa.sort_values(by='Price_euros', ascending=False)
# df.sort_values(by='likes', ascending=False)

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

#### 4.2 Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [116]:
grouped = pf.groupby('Cpu_Company')
grouped.agg({'Price_euros' : ['min', 'mean', 'max']})

            Price_euros
                    min         mean     max
Cpu_Company
AMD               199.0   560.638871  2199.0
Intel             174.0  1152.214145  6099.0
Samsung           659.0   659.000000   659.0

#### 4.3 Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [117]:
merged

,laptop_id,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,Memory_Amount2,SSD
0,506,45,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256,SSD + 1TB HDD,SSD HDD,0
1,398,32,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256,SSD,SSD,1
2,710,67,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128,SSD + 1TB HDD,SSD HDD,0
3,120,33,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024,HDD,HDD,0

In [118]:
pf.pivot_table(index='Cpu_Company', columns='Ram',
               values='Weight', aggfunc='count',
               fill_value=0)

Ram          12GB  16GB  24GB  2GB  32GB  4GB  64GB  6GB  8GB
Cpu_Company
AMD             2     3     0    1     0   31     0   13   12
Intel          23   197     3   21    17  343     1   28  607
Samsung         0     0     0    0     0    1     0    0    0

#### 4.4 Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [119]:
pf.pivot_table(index='OpSys', columns='Memory_Amount',
               values='Price_euros', aggfunc='mean',
               fill_value=0)

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
OpSys,,,,,,,,,,,,,
Android,0,0.00,0.000000,434.000000,0.000000,0.0,0,0.000000,0.000000,0,0.000000,0.000000,0.0000
Chrome OS,0,305.38,412.454545,774.333333,1275.000000,0.0,0,1559.000000,0.000000,0,2199.000000,0.000000,0.0000
Linux,0,0.00,0.000000,0.000000,742.250000,0.0,0,811.638125,389.056364,0,0.000000,581.401290,0.0000
Mac OS X,0,0.00,0.000000,0.000000,1099.000000,0.0,0,1311.994000,0.000000,0,1222.000000,0.000000,0.0000
No OS,0,0.00,0.000000,0.000000,562.140000,0.0,0,782.989286,404.675385,0,1098.500000,540.539600,594.0000
Windows 10,2249,0.00,270.001471,499.716000,1026.489167,1073.5,3100,1334.456872,664.717647,0,1911.985285,904.827906,666.9475
Windows 10 S,0,0.00,0.000000,308.995000,1039.000000,0.0,0,1668.950000,0.000000,0,2589.000000,0.000000,0.0000
Windows 7,0,0.00,0.000000,0.000000,1320.323333,1199.0,0,1846.466800,924.048333,1002,2235.396667,1539.666667,0.0000
macOS,0,0.00,0.000000,0.000000,1119.315000,0.0,0,1600.370000,0.000000,0,2180.870000,0.000000,0.0000

In [120]:
pf.pivot_table(index='OpSys', columns='Ram',
               values='Price_euros', aggfunc='mean',
               fill_value=0)

Ram,12GB,16GB,24GB,2GB,32GB,4GB,64GB,6GB,8GB
OpSys,,,,,,,,,
Android,0.000000,0.000000,0.000000,0.000000,0.000000,434.000000,0,0.000000,0.000000
Chrome OS,0.000000,2199.000000,0.000000,234.333333,0.000000,397.726316,0,0.000000,1122.000000
Linux,949.000000,974.000000,0.000000,0.000000,0.000000,417.705625,0,0.000000,814.618148
Mac OS X,0.000000,2139.970000,0.000000,0.000000,0.000000,959.000000,0,0.000000,1167.333333
No OS,0.000000,1265.316667,0.000000,0.000000,0.000000,393.980625,0,0.000000,722.674516
Windows 10,1205.998261,1916.548315,2206.333333,257.534211,3413.085882,604.317509,3975,615.206341,1190.119217
Windows 10 S,0.000000,2589.000000,0.000000,0.000000,0.000000,673.997500,0,0.000000,1668.950000
Windows 7,2299.000000,2840.400000,0.000000,0.000000,0.000000,1036.020833,0,0.000000,1739.483704
macOS,0.000000,2611.806667,0.000000,0.000000,0.000000,0.000000,0,0.000000,1490.978000

#### 5.1 Ноутбуков каких компаний и с каким процессором больше?

In [132]:
pd.crosstab(index=pf['Company'],
            columns=pf['Cpu_Company']
        ).sort_values(by=['AMD', 'Intel'])

Cpu_Company  AMD  Intel  Samsung
Company
Huawei         0      2        0
Chuwi          0      3        0
Fujitsu        0      3        0
Google         0      3        0
LG             0      3        0
Vero           0      4        0
Xiaomi         0      4        0
Microsoft      0      6        0
Mediacom       0      7        0
Razer          0      7        0
Samsung        0      8        1
Apple          0     21        0
Toshiba        0     48        0
MSI            0     54        0
Dell           0    297        0
Acer          10     93        0
Asus          11    147        0
Lenovo        16    281        0
HP            25    249        0

#### 5.2 С каким типом памяти и с каким объемом памяти больше ноутбуков?

In [136]:
pd.crosstab(index=pf['Company'], columns=pf['Cpu_Company'])
pd.crosstab(index=pf['Memory_Type'], columns=pf['Memory_Amount'])

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
Memory_Type,,,,,,,,,,,,,
Flash Storage,0,7,38,15,4,0,0,8,0,0,2,0,0
Flash Storage + 1TB HDD,0,0,0,1,0,0,0,0,0,0,0,0,0
HDD,0,0,1,0,1,0,0,0,132,0,0,224,16
HDD + 1TB HDD,0,0,0,0,0,0,0,0,0,0,0,1,0
Hybrid,0,0,0,0,0,0,0,0,0,1,0,9,0
SSD,1,3,6,1,76,5,1,412,0,0,118,14,0
SSD + 1.0TB Hybrid,0,0,0,0,0,0,0,1,0,0,1,0,0
SSD + 1TB HDD,0,0,0,0,94,0,0,73,0,0,14,2,0
SSD + 256GB SSD,0,0,0,0,0,0,0,2,0,0,1,0,0
SSD + 2TB HDD,0,0,0,0,2,0,0,10,0,0,3,0,0
SSD + 500GB HDD,0,0,0,0,0,0,0,2,0,0,0,0,0
SSD + 512GB SSD,0,0,0,0,0,0,0,0,0,0,1,0,0